### ISSUE TITLE
Visited and unvisited links are same color on Fluxxor.com

### ISSUE THREAD

**Issue by JonathanHayward** [BinaryMuse/fluxxor#103]
Per an old version of http://www.nngroup.com/articles/top-10-mistakes-web-design/ - fluxxor.com, like most websites, will be easier to navigate if visited and unvisited links are the same color.

**Comment by BinaryMuse** [comment]
Thanks, this was a total oversight on my part. I'll get this fixed and deployed today!

**Comment by JonathanHayward** [comment]
Thanks!

**Comment by JonathanHayward** [comment]
(P.S. Thank you for making Fluxxor available!)
