### ISSUE TITLE
Simplified actions syntax proposal

### ISSUE THREAD

**Issue by AlgoTrader** [BinaryMuse/fluxxor#104]
There is a frequent pattern with actions
```
var actions = {
  someAction: function(p1, p2) {
    this.dispatch("SOME_ACTION", p1, p2);
  }
}
```
if function just dispatch the action further, then simplified syntax can be implemented:
```
var actions = {
  someAction: "SOME_ACTION",
}
```

if action is string, not function, we can cal this.dispatch with action value and pass all the arguments there

**Comment by BinaryMuse** [comment]
Hey, @AlgoTrader, thanks for the idea. I like it! However, `this.dispatch` takes two parameters: the action type, and a payload object.

```javascript
var actions = {
  someAction: function(p1, p2) {
    this.dispatch("SOME_ACTION", {p1: p1, p2: p2});
  }
}
```

In the simplified syntax, how do we decide on the keys to use for the action payload? We could specify them as strings, but I'm not sure that syntax is actually better/less confusing:

```javascript
var actions = {
  someAction: ["SOME_ACTION", ["p1", "p2"]]
}
```

```javascript
var actions = {
  someAction: { type: "SOME_ACTION", payload: ["p1", "p2"] }
}
```

What do you think?

**Comment by AlgoTrader** [comment]
I tend to use pattern, where I use a zero or single parameters in actions calls:

flux.actions.shitHappened()

or 

flux.actions.complexShitHappened({stuff1:..., stuff2:..})

I never used actions with two or more parameters, I tend to wrap such things into a single object

**Comment by BinaryMuse** [comment]
This will not go into core since easy (and more flexible) to implement with a higher-order function.

```javascript
function gen(actionType) {
  return function(arg) { this.dispatch(actionType, arg); };
}

var actions = {
  someAction: gen("SOME_ACTION"),
}
```
