### ISSUE TITLE
Mixins with React 0.13 & ES6 Classes 

### ISSUE THREAD

**Issue by bkolobara** [BinaryMuse/fluxxor#110]
This post http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#mixins mentions that React will not get any mixin support for ES6 classes.

I'm starting a new project and I would like to use ES6 classes, but also keep using Fluxxor. What would be the best way to integrate Fluxxor with React without the FluxMixin & StoreWatchMixin?

**Comment by nelix** [comment]
The Fluxxor mixins are pretty simple, you can get much the same results by passing a ref to flux through the component tree and listening to stores ie: ```this.props.flux.store('Name').on('change', this.change)```

**Comment by mcharytoniuk** [comment]
You can as well use combination of [lodash's](http://lodash.com) `_.assign` and `_.bindAll`, eg.:

```JavaScript
class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    _.assign(this, StoreWatchMixin());
    _.bindAll(this);
  }
}
```
