### ISSUE TITLE
StoreWatchMixin Callbacks Not Firing In IE9

### ISSUE THREAD

**Issue by Pharserror** [BinaryMuse/fluxxor#114]
React Components in my project using mixins: [StoreWatchMixin('MyStore')] don't have their state updated after change events fire in IE9. That is, they are using some logic in the render to output different things based off of the state of the store which they are accessing through this.state. Am I confused that a component will not re-render under these circumstances?

**Comment by BinaryMuse** [comment]
I'm not aware of any reason this wouldn't be working in IE9. Do you have more concrete example code I can take a look at?

**Comment by Pharserror** [comment]
Let me put something together after I test again. I hope it's a non-issue
but I will get back to you asap.

**Comment by Pharserror** [comment]
I'm going to close this issue for now until I can get time in my schedule to test.
