### ISSUE TITLE
Should fluxxor assume that React is in the global namespace.

### ISSUE THREAD

**Issue by rollokb** [BinaryMuse/fluxxor#115]
Hey I really like this library, however I noticed that causes some problems with browserify and gulp, because it doesn't import react, it just assumes it's in the global namespace.

It may be worth including `React = require("react")` at the beginning of the files which depend in it.

**Comment by BinaryMuse** [comment]
Fluxxor doesn't require React to be in the global namespace; in fact, most of Fluxxor doesn't depend on React. When React *is* required, you're expected [to pass it in](http://fluxxor.com/documentation/flux-mixin.html) (so you can get it however you want—CommonJS, global, etc.)

**Comment by rollokb** [comment]
Apologies,

Thanks for clarifying this.

**Comment by BinaryMuse** [comment]
No problem! Sorry if it wasn't clear. Happy to change some docs up if something was confusing.
