### ISSUE TITLE
Unable to use with react-native

### ISSUE THREAD

**Issue by BinaryMuse** [BinaryMuse/fluxxor#116]
Reported in Gitter by @lazywei. Throws the following error:

![fluxxor-react-native](https://cloud.githubusercontent.com/assets/189606/7007277/212c4cca-dc3d-11e4-829e-c349dc1dc281.png)

**Comment by BinaryMuse** [comment]
Fixed in v1.5.3.

**Comment by lazywei** [comment]
:beers:

**Comment by jonaswindey** [comment]
How do you pass your flux instance to your AppRegistry.registerComponent?

**Comment by lazywei** [comment]
@jonaswindey I use context.

```
var MyRN = React.createClass({

  childContextTypes: {
    flux: React.PropTypes.object,
  },

  getChildContext() {
    return {
      flux: flux,
    };
  },

});

AppRegistry.registerComponent("MyRN", () => MyRN);
```
