### ISSUE TITLE
Doubt about actions

### ISSUE THREAD

**Issue by gabrielgiussi** [BinaryMuse/fluxxor#118]
Hi, i have a doubt about actions. How you get dispatch function in an action? Where does it come from?
var actions = {
  addTodo: function(text) {
    this.dispatch(constants.ADD_TODO, {text: text});
  },
Thanks

**Comment by BinaryMuse** [comment]
The functions inside the actions hash are copied and bound to a special object when you call `addAction(s)` or when you pass them to the `Flux` constructor. See https://github.com/BinaryMuse/fluxxor/blob/d35b6046fdafc9385ee30de1d9ae542ae592ec07/lib/flux.js#L33-42 and https://github.com/BinaryMuse/fluxxor/blob/master/lib/flux.js#L68.
