### ISSUE TITLE
ES6 Mixin Workaround

### ISSUE THREAD

**Issue by furley** [BinaryMuse/fluxxor#126]
I'm trying to work with Fluxxor in es6 syntax. Mixins aren't supported in es6, so I'm run into issues building out components. I haven't quite nailed down an elegant solution for dealing with this yet. It seems to me that the docs and examples are all es5. 

Can we add an example to the docs of how to implement a mixin workaround? Or is the easiest solution not to use es6 for now?

**Comment by BinaryMuse** [comment]
Take a look at #117 and see if that fits your bill. A fully supported solution isn't in the published version of Fluxxor yet.

**Comment by furley** [comment]
Ahh. Very helpful. I'll take a look.
