### ISSUE TITLE
Fluxxor.Flux.Stores to access stores?

### ISSUE THREAD

**Issue by droberts84** [BinaryMuse/fluxxor#127]
I'm writing a function that needs to pull data from all current `stores` for error reporting purposes.

I see that the `Flux` object has a [stores](https://github.com/BinaryMuse/fluxxor/blob/master/lib/flux.js#L29) attribute, which provides all of the data I need to implement this function, but it is not documented anywhere.

I just wanted to check if this was an anti-pattern or something you plan to change soon.  If so is there another recommended way to access every `store` registered with the `flux` instance?

**Comment by BinaryMuse** [comment]
Added a new [`Flux#getAllStores()`](http://fluxxor.com/documentation/flux.html#-fluxxor-flux-getallstores-) method in v1.7.0.
