### ISSUE TITLE
update lodash / change range

### ISSUE THREAD

**Issue by dantman** [BinaryMuse/fluxxor#128]
The current dependency value for lodash forces npm to download a second copy of an old version of lodash because the ~ is restricting lodash to an old minor release.

**Comment by BinaryMuse** [comment]
Ah, yes, this was done because of the problem reported at #120. Lodash has since been fixed, so I'll update the dep and cut a patch release later today.

**Comment by BinaryMuse** [comment]
Released fix in v1.7.1
