### ISSUE TITLE
bindActions should accept an object

### ISSUE THREAD

**Issue by dantman** [BinaryMuse/fluxxor#129]
I really don't like the pattern of using odd/even args as key/value pairs. Since the keys are strings it should be possible to accept an object and use the keys as keys and the values as values.

I understand bindActions uses this pattern so the keys can be passed from constants even though ES5 object literals can't use variables as keys. However this is perfectly possible in ES6.
```js
this.bindActions({
    [constants.ADD_TODO]: this.onAddTodo,
    [constants.TOGGLE_TODO]: this.onToggleTodo,
    [constants.CLEAR_TODOS]: this.onClearTodos
});
```

So I think it would be good for bindActions to optionally support passing an object instead of odd/even arg pairs.

**Comment by BinaryMuse** [comment]
This is supported; it's the `bindActions(actions)` form [in the docs](http://fluxxor.com/documentation/stores.html#-store-bindactions-type-handler-):

> **`Store#bindActions(type, handler[, ...])`**
> **`Store#bindActions(actions)`**

> Binds action types to methods on the store.

> [...]

> `bindActions(actions)` takes an actions hash in the same format as `spec.actions` described in `createStore`, above.

Happy to clear up the docs if it's not obvious.

**Comment by dantman** [comment]
Sorry, you're right.
