### ISSUE TITLE
Should recipe example in react-router have store sending actions?

### ISSUE THREAD

**Issue by tachang** [BinaryMuse/fluxxor#131]
I am taking a look at this code and see that the Store actually sends out an action. I thought this was frowned upon in flux?

https://github.com/BinaryMuse/fluxxor/blob/master/examples/react-router/app/stores/recipe_store.jsx#L44

**Comment by BinaryMuse** [comment]
Hey, @tachang, you can see the reason for this implementation in the discussion at https://github.com/BinaryMuse/fluxxor/pull/95#discussion_r23178351. I'll add a note to the code to that effect.
