### ISSUE TITLE
Better alternative to webpack

### ISSUE THREAD

**Issue by rwillrich** [BinaryMuse/fluxxor#14]
I was wondering if webpack is the best approach to build this library. I looked at the build file generated and looks really bloated by webpack's declarations. Also I think it is better to express external dependencies rather than bundled it together.

What do you think of we refactor the code and use some structure that enables use with CommonJS and AMD, but keeping the simplicity of the library. The source has only 7 files, with nearly 300 lines, excluding lodash functions. Maybe simply use [UMD](https://github.com/umdjs/umd) and expressing an external dependency on lodash code is the best way to go. 

What do you think?

**Comment by BinaryMuse** [comment]
The new `lodash` package uses the modular approach. Also Fluxxor will continue to use webpack for now.
