### ISSUE TITLE
Routing examples no longer work with latest version of React Router

### ISSUE THREAD

**Issue by brianfegan** [BinaryMuse/fluxxor#148]
After installing the latest version of React Router, the examples on the fluxxor site are no longer working.

**Comment by BinaryMuse** [comment]
Which version of React Router is this? If it's the recent release candidate, there'll be a new version of the example release once v1.0 is finalized. See also #142

**Comment by brianfegan** [comment]
Ah, ok. Yeah, its 1.0.0-rc3. But that's what gets pulled when you install react-router@latest.

**Comment by BinaryMuse** [comment]
I see. I think npm *always* sets the most recently published version to `@latest`. It's becoming apparent that there should probably be two versions of the example anyway, as some folks will be using the older React Router.

Thanks for the issue, but I'm going to close in favor of the other React Router 1.0 issues.
