### ISSUE TITLE
Documentation for setting dispatch interceptor is out of date

### ISSUE THREAD

**Issue by ttrmw** [BinaryMuse/fluxxor#150]
http://fluxxor.com/guides/react.html

this page references the old addon location under `React.addons`, where it's now under `ReactDOM.unstable_batchedUpdates`.

**Comment by ajsharp** [comment]
I had the same issue, and from this issue it seems like the react team is not interested in supporting / documenting it: https://github.com/facebook/react/issues/3570.

**Comment by ttrmw** [comment]
I got the impression that the team's disinterest is in 'rAF batching' which appears to be distinct from `batchedUpdates`/`unstable_batchedUpdates`. Are the react docs deficient in the latter area? I found out via the upgrade notes for  0.14

**Comment by BinaryMuse** [comment]
Based on facebook/react#5880 it looks like that won't get documented. I'll update the Fluxxor docs with an appropriate note.
