### ISSUE TITLE
In Routing mixin, what pattern should one use with an AuthStore?

### ISSUE THREAD

**Issue by braco** [BinaryMuse/fluxxor#82]
I have a mixin that captures route transitions under react-router, and it needs access to a particular Store instance:

```
module.exports = {
  statics:
    willTransitionTo: function(transition) {
       // Need to get AuthStore instance here
       // if (!AuthStore.loggedIn) { }
    }
 }
```

This would hypothetically allow for a  { mixins: [AuthenticatedRoute] } on React classes.

What pattern would you guys use that doesn't involve attaching anything to window?

**Comment by BinaryMuse** [comment]
React Router v0.11+, and especially the new 1.0.0 (currently in beta) support these sorts of patterns much more easily in other ways (rather than using a `willTransitionTo` static).
